from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.exc import IntegrityError
from . import DB_URL, Base
from models import *

class Seeder:
    """シードデータを挿入するクラス

    Attributes:
        session (sessionmaker): DB セッション
    """

    def __init__(self):
        """コンストラクタ

        DB セッションを作成する
        """
        engine = create_engine(DB_URL)
        self.session = sessionmaker(bind=engine)

    def handle(self, seeds: list[Base]) -> None:
        """シードデータを挿入する

        指定された全てのシードデータを挿入する
        プライマリーキーを指定したデータを指定することで重複データを防ぐことが可能

        Args:
            seeds (list[Base]): シードデータ
        """
        with self.session() as db:
            for seed in seeds:
                try:
                    db.add(seed)
                    db.commit()
                except IntegrityError:
                    db.rollback()

# poetry run python -m database.seed
if __name__ == "__main__":
    Seeder().handle([
        # シードデータを指定する
        Pelmanism(id=1, kansai="しんどい", default="疲れた"),
        Pelmanism(id=2, kansai="なおす", default="整理する、戻す、修理する"),
        Pelmanism(id=3, kansai="さら", default="新しい"),
        Pelmanism(id=4, kansai="シュッとしてる", default="ちゃんとしている、かっこよく見える"),
        Pelmanism(id=5, kansai="はよ", default="早く"),
        Pelmanism(id=6, kansai="ほんま", default="本当"),
        Pelmanism(id=7, kansai="おもろい", default="おもしろい"),
        Pelmanism(id=8, kansai="あかん", default="ダメ"),
        Pelmanism(id=9, kansai="ちゃう", default="違う"),
        Pelmanism(id=10, kansai="ほな", default="じゃあ、さて"),
        Pelmanism(id=11, kansai="めっちゃ", default="すごく、とても"),
        Pelmanism(id=12, kansai="せやねん", default="そうなんです"),
        Pelmanism(id=13, kansai="しゃあない", default="しょうがない、仕方ない"),
        Pelmanism(id=14, kansai="かめへん", default="構わない"),
        Pelmanism(id=15, kansai="でけへん", default="できない"),
        Pelmanism(id=16, kansai="やんな", default="そうだよね"),
        Pelmanism(id=17, kansai="どない", default="それはどうなの"),
        Pelmanism(id=18, kansai="そやかて", default="そうは言っても"),
        Pelmanism(id=19, kansai="うち", default="私"),
        Pelmanism(id=20, kansai="ほかす", default="捨てる"),
        Pelmanism(id=21, kansai="いけず", default="意地悪"),
        Pelmanism(id=22, kansai="さぶいぼ", default="鳥肌"),
        Pelmanism(id=23, kansai="かなん", default="無理、勝てる余地はない"),

        Prefecture(id=1, name="大阪"),
        Prefecture(id=2, name="京都"),
        Prefecture(id=3, name="兵庫"),
        Prefecture(id=4, name="奈良"),
        Prefecture(id=5, name="三重"),
        Prefecture(id=6, name="滋賀"),
        Prefecture(id=7, name="和歌山"),

        Quiz(id=1, prefecture_id=1, place="USJ", quiz="USJ (ユニバーサル・スタジオ・ジャパン) はどの都市にありますか？"),
        Quiz(id=2, prefecture_id=1, place="大阪城", quiz="大阪城は何世紀に建てられましたか？"),
        Quiz(id=3, prefecture_id=1, place="海遊館", quiz="海遊館は何を主な展示物としていますか？"),
        Quiz(id=4, prefecture_id=1, place="万博記念公園(太陽の塔)", quiz="万博記念公園にある太陽の塔は、どのイベントのシンボルでしたか？"),
        Quiz(id=5, prefecture_id=1, place="カップヌードルミュージアム大阪池田", quiz="カップヌードルミュージアム大阪池田は、どの有名な食品ブランドに関連していますか？"),
        Quiz(id=6, prefecture_id=1, place="道頓堀", quiz="道頓堀の川にあるどの有名な橋が観光スポットとなっていますか？"),
        Quiz(id=7, prefecture_id=1, place="新世界", quiz="新世界はどの有名なテーマパークに隣接していますか？"),
        Quiz(id=8, prefecture_id=1, place="通天閣", quiz="通天閣はどの有名なエリアに位置していますか？"),
        Quiz(id=9, prefecture_id=1, place="あべのハルカス", quiz="あべのハルカスは、どのくらいの高さを持つ建物ですか？"),
        Quiz(id=10, prefecture_id=1, place="ひらかたパーク", quiz="ひらかたパークはどの種類のテーマパークですか？"),
        Quiz(id=11, prefecture_id=1, place="天王寺動物園", quiz="天王寺動物園は何を専門としていますか？"),
        Quiz(id=12, prefecture_id=1, place="梅田スカイビル	", quiz="梅田スカイビルは、どの都市のランドマークですか？"),
        Quiz(id=13, prefecture_id=2, place="清水寺", quiz="清水寺はどの都市に位置していますか？"),
        Quiz(id=14, prefecture_id=2, place="伏見稲荷大社", quiz="伏見稲荷大社の特徴的な要素は何ですか？"),
        Quiz(id=15, prefecture_id=2, place="金閣寺", quiz="金閣寺は正式には何と呼ばれていますか？"),
        Quiz(id=16, prefecture_id=2, place="嵐山", quiz="嵐山はどの都市の観光エリアですか？"),
        Quiz(id=17, prefecture_id=2, place="竹林の道", quiz="竹林の道はどのエリアにありますか？"),
        Quiz(id=18, prefecture_id=2, place="平等院", quiz="平等院にある有名な仏像は何ですか？"),
        Quiz(id=19, prefecture_id=2, place="鴨川", quiz="鴨川はどの都市に流れていますか？"),
        Quiz(id=20, prefecture_id=3, place="若草山", quiz="若草山はどの都市に位置していますか？"),
        Quiz(id=21, prefecture_id=3, place="大神神社", quiz="大神神社はどの地域に鎮座していますか？"),
        Quiz(id=22, prefecture_id=3, place="吉野山", quiz="吉野山はどの都市の観光地ですか？"),
        Quiz(id=23, prefecture_id=3, place="奈良公園", quiz="奈良公園に自由に歩き回っている動物は何ですか？"),
        Quiz(id=24, prefecture_id=3, place="東大寺", quiz="東大寺はどの都市にありますか？"),
        Quiz(id=25, prefecture_id=4, place="有馬温泉", quiz="有馬温泉はどの都道府県にありますか？"),
        Quiz(id=26, prefecture_id=4, place="城崎温泉", quiz="城崎温泉はどの地域に位置していますか？"),
        Quiz(id=27, prefecture_id=4, place="香住温泉", quiz="香住温泉はどの海岸に近いですか？"),
        Quiz(id=28, prefecture_id=4, place="姫路城", quiz="姫路城の別名は？"),
        Quiz(id=29, prefecture_id=4, place="竹田城跡", quiz="竹田城跡はどの都道府県にありますか？"),
        Quiz(id=30, prefecture_id=4, place="明石海峡大橋", quiz="明石海峡大橋はどの都市とどの都道府県を結んでいますか？"),
        Quiz(id=31, prefecture_id=5, place="伊勢神宮", quiz="伊勢神宮の内宮に祀られている神主は誰でしょう？"),
        Quiz(id=32, prefecture_id=5, place="鳥羽水族館", quiz="日本で唯一何を飼育する水族館でしょう？"),
        Quiz(id=33, prefecture_id=5, place="おかげ横丁", quiz="おかげ横丁の名前の由来となった言葉は何でしょう？"),
        Quiz(id=34, prefecture_id=5, place="志摩スペイン村", quiz="志摩スペイン村の建物や風景は、どの国をイメージして造られていますか？"),
        Quiz(id=35, prefecture_id=6, place="琵琶湖", quiz="琵琶湖は日本最大の湖ですが、その面積はおおよそいくつ平方キロメートルでしょう？"),
        Quiz(id=36, prefecture_id=6, place="彦根城", quiz="彦根城の天守閣からの眺めで知られる景色は何でしょう？"),
        Quiz(id=37, prefecture_id=6, place="白髪神社", quiz="白髪神社に祀られている神は誰でしょう？"),
        Quiz(id=38, prefecture_id=6, place="比叡山延暦寺", quiz="延暦寺は何年に創建されたでしょう？"),
        Quiz(id=39, prefecture_id=7, place="アドベンチャーワールド", quiz="アドベンチャーワールドの特徴的な動物は何でしょうか？"),
        Quiz(id=40, prefecture_id=7, place="とれとれ市場", quiz="「とれとれ市場」があるのは次のどの地域でしょうか？"),
        Quiz(id=41, prefecture_id=7, place="那智の滝", quiz="「那智の滝」は日本のどの地域に位置していますか？"),
        Quiz(id=42, prefecture_id=7, place="和歌山城", quiz="和歌山城はどの武将が築城した城でしょうか？"),

        QuizChoice(id=1, quiz_id=1, choice="東京", is_answer=False),
        QuizChoice(id=2, quiz_id=1, choice="大阪", is_answer=True),
        QuizChoice(id=3, quiz_id=1, choice="京都", is_answer=False),
        QuizChoice(id=4, quiz_id=1, choice="福岡", is_answer=False),
        QuizChoice(id=5, quiz_id=2, choice="15世紀", is_answer=False),
        QuizChoice(id=6, quiz_id=2, choice="16世紀", is_answer=False),
        QuizChoice(id=7, quiz_id=2, choice="17世紀", is_answer=True),
        QuizChoice(id=8, quiz_id=2, choice="18世紀", is_answer=False),
        QuizChoice(id=9, quiz_id=3, choice="自然史", is_answer=False),
        QuizChoice(id=10, quiz_id=3, choice="航空機", is_answer=False),
        QuizChoice(id=11, quiz_id=3, choice="水族館", is_answer=True),
        QuizChoice(id=12, quiz_id=3, choice="軍事史", is_answer=False),
        QuizChoice(id=13, quiz_id=4, choice="世界博覧会", is_answer=False),
        QuizChoice(id=14, quiz_id=4, choice="オリンピック", is_answer=False),
        QuizChoice(id=15, quiz_id=4, choice="花博覧会", is_answer=False),
        QuizChoice(id=16, quiz_id=4, choice="万国博覧会", is_answer=True),
        QuizChoice(id=17, quiz_id=5, choice="すきやき", is_answer=False),
        QuizChoice(id=18, quiz_id=5, choice="おでん", is_answer=False),
        QuizChoice(id=19, quiz_id=5, choice="カップヌードル", is_answer=True),
        QuizChoice(id=20, quiz_id=5, choice="そば", is_answer=False),
        QuizChoice(id=21, quiz_id=6, choice="えびす橋", is_answer=True),
        QuizChoice(id=22, quiz_id=6, choice="なんば大橋", is_answer=False),
        QuizChoice(id=23, quiz_id=6, choice="鉄砲洲橋", is_answer=False),
        QuizChoice(id=24, quiz_id=6, choice="龍馬橋", is_answer=False),
        QuizChoice(id=25, quiz_id=7, choice="東京ディズニーランド", is_answer=False),
        QuizChoice(id=26, quiz_id=7, choice="ユニバーサル・スタジオ・ジャパン", is_answer=True),
        QuizChoice(id=27, quiz_id=7, choice="東京ディズニーシー", is_answer=False),
        QuizChoice(id=28, quiz_id=7, choice="富士急ハイランド", is_answer=False),
        QuizChoice(id=29, quiz_id=8, choice="なんば", is_answer=False),
        QuizChoice(id=30, quiz_id=8, choice="梅田", is_answer=False),
        QuizChoice(id=31, quiz_id=8, choice="新大阪", is_answer=False),
        QuizChoice(id=32, quiz_id=8, choice="天王寺", is_answer=True),
        QuizChoice(id=33, quiz_id=9, choice="200メートル", is_answer=False),
        QuizChoice(id=34, quiz_id=9, choice="250メートル", is_answer=False),
        QuizChoice(id=35, quiz_id=9, choice="300メートル", is_answer=True),
        QuizChoice(id=36, quiz_id=9, choice="350メートル", is_answer=False),
        QuizChoice(id=37, quiz_id=10, choice="水族館", is_answer=False),
        QuizChoice(id=38, quiz_id=10, choice="花園", is_answer=False),
        QuizChoice(id=39, quiz_id=10, choice="アミューズメントパーク", is_answer=True),
        QuizChoice(id=40, quiz_id=10, choice="歴史博物館", is_answer=False),
        QuizChoice(id=41, quiz_id=11, choice="海洋生物", is_answer=False),
        QuizChoice(id=42, quiz_id=11, choice="熱帯鳥類", is_answer=False),
        QuizChoice(id=43, quiz_id=11, choice="哺乳動物", is_answer=True),
        QuizChoice(id=44, quiz_id=11, choice="爬虫類", is_answer=False),
        QuizChoice(id=45, quiz_id=12, choice="京都", is_answer=False),
        QuizChoice(id=46, quiz_id=12, choice="大阪", is_answer=True),
        QuizChoice(id=47, quiz_id=12, choice="神戸", is_answer=False),
        QuizChoice(id=48, quiz_id=12, choice="奈良", is_answer=False),
        QuizChoice(id=49, quiz_id=13, choice="京都", is_answer=True),
        QuizChoice(id=50, quiz_id=13, choice="東京", is_answer=False),
        QuizChoice(id=51, quiz_id=13, choice="大阪", is_answer=False),
        QuizChoice(id=52, quiz_id=13, choice="福岡", is_answer=False),
        QuizChoice(id=53, quiz_id=14, choice="千本鳥居", is_answer=True),
        QuizChoice(id=54, quiz_id=14, choice="五重塔", is_answer=False),
        QuizChoice(id=55, quiz_id=14, choice="金箔", is_answer=False),
        QuizChoice(id=56, quiz_id=14, choice="龍の彫刻", is_answer=False),
        QuizChoice(id=57, quiz_id=15, choice="東山慈照寺", is_answer=False),
        QuizChoice(id=58, quiz_id=15, choice="銅閣寺", is_answer=False),
        QuizChoice(id=59, quiz_id=15, choice="北山鹿苑寺", is_answer=True),
        QuizChoice(id=60, quiz_id=15, choice="鹿門寺", is_answer=False),
        QuizChoice(id=61, quiz_id=16, choice="京都", is_answer=True),
        QuizChoice(id=62, quiz_id=16, choice="東京", is_answer=False),
        QuizChoice(id=63, quiz_id=16, choice="大阪", is_answer=False),
        QuizChoice(id=64, quiz_id=16, choice="福岡", is_answer=False),
        QuizChoice(id=65, quiz_id=17, choice="青山", is_answer=False),
        QuizChoice(id=66, quiz_id=17, choice="渋谷", is_answer=False),
        QuizChoice(id=67, quiz_id=17, choice="嵐山", is_answer=True),
        QuizChoice(id=68, quiz_id=17, choice="金沢", is_answer=False),
        QuizChoice(id=69, quiz_id=18, choice="千手観音", is_answer=False),
        QuizChoice(id=70, quiz_id=18, choice="阿弥陀如来", is_answer=True),
        QuizChoice(id=71, quiz_id=18, choice="弥勒菩薩", is_answer=False),
        QuizChoice(id=72, quiz_id=18, choice="観音菩薩", is_answer=False),
        QuizChoice(id=73, quiz_id=19, choice="京都", is_answer=True),
        QuizChoice(id=74, quiz_id=19, choice="東京", is_answer=False),
        QuizChoice(id=75, quiz_id=19, choice="大阪", is_answer=False),
        QuizChoice(id=76, quiz_id=19, choice="福岡", is_answer=False),
        QuizChoice(id=77, quiz_id=20, choice="京都", is_answer=False),
        QuizChoice(id=78, quiz_id=20, choice="東京", is_answer=False),
        QuizChoice(id=79, quiz_id=20, choice="大阪", is_answer=False),
        QuizChoice(id=80, quiz_id=20, choice="奈良", is_answer=True),
        QuizChoice(id=81, quiz_id=21, choice="吉野", is_answer=True),
        QuizChoice(id=82, quiz_id=21, choice="生駒", is_answer=False),
        QuizChoice(id=83, quiz_id=21, choice="高市", is_answer=False),
        QuizChoice(id=84, quiz_id=21, choice="大和高田", is_answer=False),
        QuizChoice(id=85, quiz_id=22, choice="京都", is_answer=False),
        QuizChoice(id=86, quiz_id=22, choice="東京", is_answer=False),
        QuizChoice(id=87, quiz_id=22, choice="大阪", is_answer=False),
        QuizChoice(id=88, quiz_id=22, choice="奈良", is_answer=True),
        QuizChoice(id=89, quiz_id=23, choice="キツネ", is_answer=False),
        QuizChoice(id=90, quiz_id=23, choice="鹿", is_answer=True),
        QuizChoice(id=91, quiz_id=23, choice="猿", is_answer=False),
        QuizChoice(id=92, quiz_id=23, choice="うさぎ", is_answer=False),
        QuizChoice(id=93, quiz_id=24, choice="京都", is_answer=False),
        QuizChoice(id=94, quiz_id=24, choice="東京", is_answer=False),
        QuizChoice(id=95, quiz_id=24, choice="大阪", is_answer=False),
        QuizChoice(id=96, quiz_id=24, choice="奈良", is_answer=True),
        QuizChoice(id=97, quiz_id=25, choice="静岡", is_answer=False),
        QuizChoice(id=98, quiz_id=25, choice="兵庫", is_answer=True),
        QuizChoice(id=99, quiz_id=25, choice="福岡", is_answer=False),
        QuizChoice(id=100, quiz_id=25, choice="高知", is_answer=False),
        QuizChoice(id=101, quiz_id=26, choice="九州", is_answer=False),
        QuizChoice(id=102, quiz_id=26, choice="関東", is_answer=False),
        QuizChoice(id=103, quiz_id=26, choice="中国", is_answer=False),
        QuizChoice(id=104, quiz_id=26, choice="近畿", is_answer=True),
        QuizChoice(id=105, quiz_id=27, choice="太平洋", is_answer=False),
        QuizChoice(id=106, quiz_id=27, choice="日本海", is_answer=True),
        QuizChoice(id=107, quiz_id=27, choice="瀬戸内海", is_answer=False),
        QuizChoice(id=108, quiz_id=27, choice="東シナ海", is_answer=False),
        QuizChoice(id=109, quiz_id=28, choice="白鷺城", is_answer=True),
        QuizChoice(id=110, quiz_id=28, choice="子午線城", is_answer=False),
        QuizChoice(id=111, quiz_id=28, choice="鶴城", is_answer=False),
        QuizChoice(id=112, quiz_id=28, choice="城崎城", is_answer=False),
        QuizChoice(id=113, quiz_id=29, choice="京都府", is_answer=False),
        QuizChoice(id=114, quiz_id=29, choice="大阪府", is_answer=False),
        QuizChoice(id=115, quiz_id=29, choice="奈良県", is_answer=False),
        QuizChoice(id=116, quiz_id=29, choice="兵庫県", is_answer=True),
        QuizChoice(id=117, quiz_id=30, choice="神戸市 - 香川県", is_answer=True),
        QuizChoice(id=118, quiz_id=30, choice="神戸市 - 徳島県", is_answer=False),
        QuizChoice(id=119, quiz_id=30, choice="明石市 - 香川県", is_answer=False),
        QuizChoice(id=120, quiz_id=30, choice="明石市 - 徳島県", is_answer=False),
        QuizChoice(id=121, quiz_id=31, choice="素戔嗚尊", is_answer=False),
        QuizChoice(id=122, quiz_id=31, choice="倭建命", is_answer=False),
        QuizChoice(id=123, quiz_id=31, choice="天照大御神", is_answer=True),
        QuizChoice(id=124, quiz_id=31, choice="菅原道真", is_answer=False),
        QuizChoice(id=125, quiz_id=32, choice="ジュゴン", is_answer=True),
        QuizChoice(id=126, quiz_id=32, choice="トド", is_answer=False),
        QuizChoice(id=127, quiz_id=32, choice="シャチ", is_answer=False),
        QuizChoice(id=128, quiz_id=32, choice="ブタ", is_answer=False),
        QuizChoice(id=129, quiz_id=33, choice="古今和歌集", is_answer=False),
        QuizChoice(id=130, quiz_id=33, choice="お蔭で", is_answer=True),
        QuizChoice(id=131, quiz_id=33, choice="御蔭町", is_answer=False),
        QuizChoice(id=132, quiz_id=33, choice="影絵", is_answer=False),
        QuizChoice(id=133, quiz_id=34, choice="ノルウェー", is_answer=False),
        QuizChoice(id=134, quiz_id=34, choice="スペイン", is_answer=True),
        QuizChoice(id=135, quiz_id=34, choice="イギリス", is_answer=False),
        QuizChoice(id=136, quiz_id=34, choice="ドイツ", is_answer=False),
        QuizChoice(id=137, quiz_id=35, choice="約660k㎡", is_answer=False),
        QuizChoice(id=138, quiz_id=35, choice="約665k㎡", is_answer=False),
        QuizChoice(id=139, quiz_id=35, choice="約670k㎡", is_answer=True),
        QuizChoice(id=140, quiz_id=35, choice="約675k㎡", is_answer=False),
        QuizChoice(id=141, quiz_id=36, choice="琵琶湖", is_answer=True),
        QuizChoice(id=142, quiz_id=36, choice="あべのハルカス", is_answer=False),
        QuizChoice(id=143, quiz_id=36, choice="京都タワー", is_answer=False),
        QuizChoice(id=144, quiz_id=36, choice="通天閣", is_answer=False),
        QuizChoice(id=145, quiz_id=37, choice="猿田彦命", is_answer=True),
        QuizChoice(id=146, quiz_id=37, choice="天照大御神", is_answer=False),
        QuizChoice(id=147, quiz_id=37, choice="市杵島姫命", is_answer=False),
        QuizChoice(id=148, quiz_id=37, choice="菅原道真", is_answer=False),
        QuizChoice(id=149, quiz_id=38, choice="768年", is_answer=False),
        QuizChoice(id=150, quiz_id=38, choice="778年", is_answer=True),
        QuizChoice(id=151, quiz_id=38, choice="788年", is_answer=False),
        QuizChoice(id=152, quiz_id=38, choice="798年", is_answer=False),
        QuizChoice(id=153, quiz_id=39, choice="シロクマ", is_answer=False),
        QuizChoice(id=154, quiz_id=39, choice="ライオン", is_answer=False),
        QuizChoice(id=155, quiz_id=39, choice="キリン", is_answer=False),
        QuizChoice(id=156, quiz_id=39, choice="パンダ", is_answer=True),
        QuizChoice(id=157, quiz_id=40, choice="和歌山市", is_answer=False),
        QuizChoice(id=158, quiz_id=40, choice="紀の川市", is_answer=False),
        QuizChoice(id=159, quiz_id=40, choice="串本町", is_answer=False),
        QuizChoice(id=160, quiz_id=40, choice="西牟婁郡", is_answer=True),
        QuizChoice(id=161, quiz_id=41, choice="静岡県", is_answer=False),
        QuizChoice(id=162, quiz_id=41, choice="和歌山県", is_answer=True),
        QuizChoice(id=163, quiz_id=41, choice="長野県", is_answer=False),
        QuizChoice(id=164, quiz_id=41, choice="岐阜県", is_answer=False),
        QuizChoice(id=165, quiz_id=42, choice="織田信長", is_answer=False),
        QuizChoice(id=166, quiz_id=42, choice="徳川家康", is_answer=False),
        QuizChoice(id=167, quiz_id=42, choice="黒田官兵衛", is_answer=False),
        QuizChoice(id=168, quiz_id=42, choice="豊臣秀吉", is_answer=True),
    ])
